# https://docs.codecov.com/docs/commit-status#project-status

coverage:
  status:
    project:
      default:
        target: 0% # Make CI always succeed
        threshold: 100% # Make CI always succeed
    patch:
      default:
        target: 0% # Make CI always succeed
        threshold: 100% # Make CI always succeed

comment:
  show_carryforward_flags: true

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - name_prefix: project-
        type: project
        target: 0% # Make CI always succeed
        threshold: 100% # Make CI always succeed
      - name_prefix: patch-
        type: patch
        target: 0% # Make CI always succeed
        threshold: 100% # Make CI always succeed
